name: CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker settings
        run: |
          if [ -f /etc/docker/daemon.json ]; then
            sudo sed -i 's/ }/, \"max-concurrent-uploads\": 2 }/' /etc/docker/daemon.json
            sudo systemctl restart docker
          else
            echo "/etc/docker/daemon.json does not exist."
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install doctl CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build a container image
        run: docker build -t ${{ secrets.REGISTRY_NAME }}/comment-api:$(echo $GITHUB_SHA | head -c7) .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Remove all old images from DigitalOcean Container Registry
        run: |
          REPO_NAME="comment-api"
          IMAGE_TAGS=$(doctl registry repository list-tags $REPO_NAME | grep -o "sha.*" | tr -d '[:space:]')
          if [ ! -z "$IMAGE_TAGS" ]; then
            doctl registry repository delete-manifest $REPO_NAME $IMAGE_TAGS --force
          else
            echo "No images to remove from registry."
          fi
      - name: Push the image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/comment-api:$(echo $GITHUB_SHA | head -c7)
